apiVersion: apps/v1
kind: Deployment
metadata: { name: urlshortener, labels: { app: urlshortener } }
spec:
  replicas: 1
  selector: { matchLabels: { app: urlshortener } }
  template:
    metadata: { labels: { app: urlshortener } }
    spec:
      containers:
      - name: app
        image: urlshortener:124
        imagePullPolicy: Never
        ports: [{ containerPort: 3000 }]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: REDIS_URL
          value: "redis://redis-master:6379"
---
apiVersion: v1
kind: Service
metadata: { name: urlshortener }
spec:
  selector: { app: urlshortener }
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urlshortener
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: short.tlawl.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: { service: { name: urlshortener, port: { number: 80 } } }
