apiVersion: batch/v1
kind: Job
metadata:
  name: dast-scan
  namespace: urlshortener-staging
spec:
  template:
    spec:
      containers:
      - name: zap
        image: ghcr.io/zaproxy/zaproxy:stable
        command: ["/zap/zap-baseline.py"]
        args: 
        - "-t"
        - "http://short.tlawl.com"
        - "-J"
        - "/zap/wrk/report.json"
        - "-r"
        - "/zap/wrk/report.html"
        volumeMounts:
        - name: reports
          mountPath: /zap/wrk
      volumes:
      - name: reports
        emptyDir: {}
      restartPolicy: Never