apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZXhhbXBsZS5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiSGFyYm9yMTIzNDUiLCJhdXRoIjoiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9In19fQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-token
  namespace: jenkins
stringData:
  token: "xoxb-your-slack-bot-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-token
  namespace: jenkins
stringData:
  token: "squ_your-sonarqube-token"