apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: { name: external-dns, namespace: kube-system }
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns
      version: 8.5.0               # 예시 버전
      sourceRef: { kind: HelmRepository, name: bitnami, namespace: flux-system }
  values:
    provider: aws
    policy: sync
    txtOwnerId: urlshortener-eks
    domainFilters: ["example.com"]  # 실제 도메인으로 교체
    serviceAccount:
      create: true
      name: external-dns
  # IRSA도 같은 방식으로 주입 가능 (원하면 ConfigMap에 extDnsRoleArn도 넣어라)

