apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns
      version: 8.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    provider: aws
    policy: sync
    txtOwnerId: urlshortener-eks
    domainFilters: ["tlawl.com"]  # ← 너의 실제 도메인으로 교체
    serviceAccount:
      create: true
      name: external-dns
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::219967435143:role/urlshortener-externaldns 
  # IRSA도 같은 방식으로 주입 가능 (원하면 ConfigMap에 extDnsRoleArn도 넣어라)

