apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      version: 5.7.15
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    controller:
      admin:
        username: admin
        password: admin123
      serviceType: ClusterIP
      installPlugins:
        - kubernetes:4246.v5a_12b_1fe120e
        - workflow-aggregator:596.v8c21c963d92d
        - git:5.4.1
        - configuration-as-code:1810.v9b_c30a_249a_4c
        - docker-workflow:580.vc0c340686b_54
        - pipeline-stage-view:2.34
        - slack:631.v40deea_40323b
        - sonar:2.17.2
        - build-timeout:1.32
        - timestamper:1.27
      JCasC:
        defaultConfig: true
        configScripts:
          jenkins-config: |
            jenkins:
              systemMessage: "DevSecOps CI/CD Pipeline"
            unclassified:
              slackNotifier:
                teamDomain: "your-workspace"
                token: "${SLACK_TOKEN}"
                channel: "#ci-cd-alerts"
              sonarGlobalConfiguration:
                installations:
                  - name: "SonarQube"
                    serverUrl: "http://sonarqube:9000"
                    credentialsId: "sonar-token"
    agent:
      enabled: true
      image:
        repository: jenkins/inbound-agent
        tag: latest
    persistence:
      enabled: false
    serviceAccount:
      create: true
    rbac:
      create: true