apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: urlshortener-staging
spec:
  interval: 1m
  chart:
    spec:
      chart: redis
      version: 20.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 1
      persistence:
        enabled: false