apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 1m
  chart:
    spec:
      chart: sonarqube
      version: 10.7.0
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  values:
    postgresql:
      enabled: true
      auth:
        postgresPassword: sonar123
        password: sonar123
      primary:
        persistence:
          enabled: false
    sonarqube:
      adminPassword: admin123
    ingress:
      enabled: false
    persistence:
      enabled: true
      size: 5Gi