apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: { name: addons, namespace: flux-system }
spec:
  interval: 1m
  sourceRef: { kind: GitRepository, name: infra-aws-eks }
  path: ./gitops/addons
  prune: true
  wait: true
