apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata: { name: infra-aws-eks, namespace: flux-system }
spec:
  interval: 1m
  url: https://github.com/Jiwon-sim/infra-aws-eks.git
  ref: { branch: main }
  ignore: |
    /*
    !/gitops

